### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by WillGeller** [NordicPlayground/Nordic-Thingy52-Thingyjs#11]
Opened index.html in Chromium for windows 10 which supports web bluetooth now. But clicking connect does nothing. I don't think the script `type=module` is running at all. The new react app is running fine and connecting to the thingy but it is overkill for what I need and this node module looks like just what I need.

FYI I am working on bridging thingy motion data to web midi using https://github.com/djipco/webmidi :).

**Comment by williamtfalch** [comment]
Thanks for pointing that out, @WillGeller , we will alter the documentation.
