### ISSUE TITLE
simple instruction

### ISSUE THREAD

**Issue by Yury777** [NordicPlayground/Nordic-Thingy52-Thingyjs#13]
Hello!
Can you write a simple manual for using Nordic-Thingy52-Thingyjs on a raspberry pi3?

**Comment by williamtfalch** [comment]
Hi,

While it may be possible to do this, I would rather point you in the direction of our Node.js library for Thingy52, which supports Raspberry Pi :)

Link: https://github.com/NordicPlayground/Nordic-Thingy52-Nodejs/blob/master/RASPBERRYPI.md
